//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adicom.Web.Controls {
    
    public partial class UCFooter {
        protected Localization.LocalizedLiteral footerLang;
        protected Localization.LocalizedLiteral LocalizedLiteral5;
        protected Localization.LocalizedLiteral LocalizedLiteral1;
        protected Localization.LocalizedLiteral LocalizedLiteral6;
    }
}
