//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adicom.Web {
    
    
    public partial class callcenter {
        
        /// <summary>
        /// UCCallCenterLeft1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Adicom.Web.Controls.UCCallCenterLeft UCCallCenterLeft1;
        
        /// <summary>
        /// UCCallCenter1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Adicom.Web.Controls.UCCallCenter UCCallCenter1;
    }
}
